export const dbName = "learn-dynamodb"; // if you have a different table name, please update it here

export const phoneRegex = /^\d{10}$/;
export const emailRegex = /^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$/;
export const zipcodeRegex = /^\d{6}$/;

export const pageType = {
  chapter: "chapter",
  section: "section",
};

export const chapters = [
  {
    id: 1,
    chapter: 0,
    type: pageType.chapter,
    title: "Introduction",
    href: "/",
  },
  {
    id: 2,
    chapter: 0,
    type: pageType.chapter,
    title: "Requirements",
    href: "/requirements",
  },
  {
    id: 3,
    chapter: 1,
    type: pageType.chapter,
    title: "Chapter 1: What is DynamoDB?",
    href: "/chapter_1",
  },
  {
    id: 4,
    chapter: 1,
    type: pageType.section,
    title: "1.1: Key Properties of DynamoDB",
    href: "/chapter_1/1.1",
  },
  {
    id: 5,
    chapter: 1,
    type: pageType.section,
    title: "1.2: When to use DynamoDB?",
    href: "/chapter_1/1.2",
  },
  {
    id: 6,
    chapter: 2,
    type: pageType.chapter,
    title: "Chapter 2: Core Concepts of DynamoDB?",
    href: "/chapter_2",
  },
  {
    id: 7,
    chapter: 2,
    type: pageType.section,
    title: "2.1: Basic Vocabulary",
    href: "/chapter_2/2.1",
  },
  {
    id: 8,
    chapter: 2,
    type: pageType.section,
    title: "2.2: A Deeper Look: Primary keys and secondary indexes",
    href: "/chapter_2/2.2",
  },
  {
    id: 9,
    chapter: 2,
    type: pageType.section,
    title: "2.3: The importance of item collections",
    href: "/chapter_2/2.3",
  },
  {
    id: 10,
    chapter: 3,
    type: pageType.chapter,
    title: "Chapter 3: Advanced Concepts",
    href: "/chapter_3",
  },
  {
    id: 11,
    chapter: 3,
    type: pageType.section,
    title: "3.1: DynamoDB Streams",
    href: "/chapter_3/3.1",
  },
  {
    id: 12,
    chapter: 3,
    type: pageType.section,
    title: "3.2: Time-to-live (TTL)",
    href: "/chapter_3/3.2",
  },
  {
    id: 13,
    chapter: 3,
    type: pageType.section,
    title: "3.3: Partitions",
    href: "/chapter_3/3.3",
  },
  {
    id: 14,
    chapter: 3,
    type: pageType.section,
    title: "3.4: Consistency",
    href: "/chapter_3/3.4",
  },
  {
    id: 15,
    chapter: 3,
    type: pageType.section,
    title: "3.5: DynamoDB Limits",
    href: "/chapter_3/3.5",
  },
  {
    id: 16,
    chapter: 3,
    type: pageType.section,
    title: "3.6: Overloading keys and indexes",
    href: "/chapter_3/3.6",
  },
  {
    id: 17,
    chapter: 4,
    type: pageType.chapter,
    title: "Chapter 4: The Three API Action Types",
    href: "/chapter_4",
  },
  {
    id: 18,
    chapter: 4,
    type: pageType.section,
    title: "4.1: Item-based actions",
    href: "/chapter_4/4.1",
  },
  {
    id: 19,
    chapter: 4,
    type: pageType.section,
    title: "4.2: Query",
    href: "/chapter_4/4.2",
  },
  {
    id: 20,
    chapter: 4,
    type: pageType.section,
    title: "4.3: Scan",
    href: "/chapter_4/4.3",
  },
  {
    id: 21,
    chapter: 4,
    type: pageType.section,
    title: "4.4: How DynamoDB enforces efficiency",
    href: "/chapter_4/4.4",
  },
  {
    id: 22,
    chapter: 5,
    type: pageType.chapter,
    title: "Chapter 5: Using the DynamoDB API",
    href: "/chapter_5",
  },
  {
    id: 23,
    chapter: 5,
    type: pageType.section,
    title: "5.1: Learn how expression names and values work",
    href: "/chapter_5/5.1",
  },
  {
    id: 24,
    chapter: 5,
    type: pageType.section,
    title: "5.2: Don’t use an ORM",
    href: "/chapter_5/5.2",
  },
  {
    id: 26,
    chapter: 5,
    type: pageType.section,
    title: "5.3: Understand the optional properties on individual requests",
    href: "/chapter_5/5.3",
  },
  {
    id: 27,
    chapter: 6,
    type: pageType.chapter,
    title: "Chapter 6: Expressions",
    href: "/chapter_6",
  },
  {
    id: 28,
    chapter: 6,
    type: pageType.section,
    title: "6.1: Key Condition Expressions",
    href: "/chapter_6/6.1",
  },
  {
    id: 29,
    chapter: 6,
    type: pageType.section,
    title: "6.2: Filter Expressions",
    href: "/chapter_6/6.2",
  },
  {
    id: 30,
    chapter: 6,
    type: pageType.section,
    title: "6.3: Projection expressions",
    href: "/chapter_6/6.3",
  },
  {
    id: 31,
    chapter: 6,
    type: pageType.section,
    title: "6.4: Condition Expressions",
    href: "/chapter_6/6.4",
  },
  {
    id: 32,
    chapter: 6,
    type: pageType.section,
    title: "6.5: Update Expressions",
    href: "/chapter_6/6.5",
  },
  {
    id: 33,
    chapter: 7,
    type: pageType.chapter,
    title: "Chapter 7: How to approach data modeling in DynamoDB",
    href: "/chapter_7",
  },
  {
    id: 34,
    chapter: 7,
    type: pageType.section,
    title: "7.1: Differences with relational databases",
    href: "/chapter_7/7.1",
  },
  {
    id: 35,
    chapter: 7,
    type: pageType.section,
    title: "7.2: Steps for Modeling with DynamoDB",
    href: "/chapter_7/7.2",
  },
  {
    id: 36,
    chapter: 8,
    type: pageType.chapter,
    title: "8. The What, Why, and When of Single-Table Design in DynamoDB",
    href: "/chapter_8",
  },
  {
    id: 37,
    chapter: 8,
    type: pageType.section,
    title: "8.1: What is single-table design",
    href: "/chapter_8/8.1",
  },
  {
    id: 38,
    chapter: 8,
    type: pageType.section,
    title: "8.2: Downsides of a single-table design",
    href: "/chapter_8/8.2",
  },
  {
    id: 39,
    chapter: 8,
    type: pageType.section,
    title: "8.3: When not to use single-table design",
    href: "/chapter_8/8.3",
  },
  {
    id: 40,
    chapter: 9,
    type: pageType.chapter,
    title: "9. From modeling to implementation",
    href: "/chapter_9",
  },
  {
    id: 41,
    chapter: 9,
    type: pageType.section,
    title: "9.1: Separate application attributes from your indexing attributes",
    href: "/chapter_9/9.1",
  },
  {
    id: 42,
    chapter: 9,
    type: pageType.section,
    title:
      "9.2: Implement your data model at the very boundary of your application",
    href: "/chapter_9/9.2",
  },
  {
    id: 43,
    chapter: 9,
    type: pageType.section,
    title: "9.3: Don’t reuse attributes across multiple indexes",
    href: "/chapter_9/9.3",
  },
  {
    id: 44,
    chapter: 9,
    type: pageType.section,
    title: "9.4: Add a 'Type' attribute to every item",
    href: "/chapter_9/9.4",
  },
  {
    id: 45,
    chapter: 9,
    type: pageType.section,
    title: "9.5: Write scripts to help debug access patterns",
    href: "/chapter_9/9.5",
  },
  {
    id: 46,
    chapter: 9,
    type: pageType.section,
    title: "9.6: Shorten attribute names to save storage",
    href: "/chapter_9/9.6",
  },
  {
    id: 47,
    chapter: 10,
    type: pageType.chapter,
    title: "10. The Importance of Strategies",
    href: "/chapter_10",
  },
  {
    id: 48,
    chapter: 11,
    type: pageType.chapter,
    title: "11. Strategies for one-to-many relationships",
    href: "/chapter_11",
  },
];
