export const dbName = "learn-dynamodb"; // if you have a different table name, please update it here

export const pageType = {
  chapter: "chapter",
  section: "section",
};

export const chapters = [
  {
    id: 1,
    chapter: 0,
    type: pageType.chapter,
    title: "Introduction",
    href: "/",
  },
  {
    id: 2,
    chapter: 0,
    type: pageType.chapter,
    title: "Requirements",
    href: "/requirements",
  },
  {
    id: 3,
    chapter: 1,
    type: pageType.chapter,
    title: "Chapter 1: What is DynamoDB?",
    href: "/chapter_1",
  },
  {
    id: 4,
    chapter: 1,
    type: pageType.section,
    title: "1.1: Key Properties of DynamoDB",
    href: "/chapter_1/1.1",
  },
  {
    id: 5,
    chapter: 1,
    type: pageType.section,
    title: "1.2: When to use DynamoDB?",
    href: "/chapter_1/1.2",
  },
  {
    id: 6,
    chapter: 2,
    type: pageType.chapter,
    title: "Chapter 2: Core Concepts of DynamoDB?",
    href: "/chapter_2",
  },
  {
    id: 7,
    chapter: 2,
    type: pageType.section,
    title: "2.1: Basic Vocabulary",
    href: "/chapter_2/2.1",
  },
  {
    id: 8,
    chapter: 2,
    type: pageType.section,
    title: "2.2: A Deeper Look: Primary keys and secondary indexes",
    href: "/chapter_2/2.2",
  },
  {
    id: 9,
    chapter: 2,
    type: pageType.section,
    title: "2.3: The importance of item collections",
    href: "/chapter_2/2.3",
  },
  {
    id: 10,
    chapter: 3,
    type: pageType.chapter,
    title: "Chapter 3: Advanced Concepts",
    href: "/chapter_3",
  },
  {
    id: 11,
    chapter: 3,
    type: pageType.section,
    title: "3.1: DynamoDB Streams",
    href: "/chapter_3/3.1",
  },
  {
    id: 12,
    chapter: 3,
    type: pageType.section,
    title: "3.2: Time-to-live (TTL)",
    href: "/chapter_3/3.2",
  },
  {
    id: 13,
    chapter: 3,
    type: pageType.section,
    title: "3.3: Partitions",
    href: "/chapter_3/3.3",
  },
  {
    id: 14,
    chapter: 3,
    type: pageType.section,
    title: "3.4: Consistency",
    href: "/chapter_3/3.4",
  },
  {
    id: 15,
    chapter: 3,
    type: pageType.section,
    title: "3.5: DynamoDB Limits",
    href: "/chapter_3/3.5",
  },
  {
    id: 16,
    chapter: 3,
    type: pageType.section,
    title: "3.6: Overloading keys and indexes",
    href: "/chapter_3/3.6",
  },
  {
    id: 17,
    chapter: 4,
    type: pageType.chapter,
    title: "Chapter 4: The Three API Action Types",
    href: "/chapter_4",
  },
  {
    id: 18,
    chapter: 4,
    type: pageType.section,
    title: "4.1: Item-based actions",
    href: "/chapter_4/4.1",
  },
  {
    id: 19,
    chapter: 4,
    type: pageType.section,
    title: "4.2: Query",
    href: "/chapter_4/4.2",
  },
  {
    id: 20,
    chapter: 4,
    type: pageType.section,
    title: "4.3: Scan",
    href: "/chapter_4/4.3",
  },
  {
    id: 21,
    chapter: 4,
    type: pageType.section,
    title: "4.4: How DynamoDB enforces efficiency",
    href: "/chapter_4/4.4",
  },
  {
    id: 22,
    chapter: 5,
    type: pageType.chapter,
    title: "Chapter 5: Using the DynamoDB API",
    href: "/chapter_5",
  },
];
